#MOSTRA A VERSAO DO BANCO DE DADOS
SELECT VERSION();

#MOSTRA AS INSTANCIAS DE BANCOS DISPONIVEIS
SHOW DATABASES;

#CRIAR UMA INSTANCIA DE BANCO DE DADOS
CREATE DATABASE BANCO;

#APAGAR O BANCO DE DADOS
DROP DATABASE BANCO;

#CONECTAR A INSTANCIA DO BANCO DE DADOS
USE BANCO;

#MOSTRA TODAS AS TABELAS DO BANCO
SHOW TABLES;

#-------------------------------------------------------

#CRIANDO TABELAS 

#CRIANDO A TABELA CLIENTE
CREATE TABLE cliente (
	cli_cpf INT PRIMARY KEY,
	cli_nome VARCHAR(255) NOT NULL,
	cli_rua VARCHAR(255) NOT NULL,
	cli_numero INT NOT NULL,
	cli_bairro VARCHAR(255) NOT NULL,
	cli_telefone VARCHAR(11) NOT NULL
	);
#MOSTRA OS ATRIBUTOS DA TABELA
DESCRIBE cliente;

#APAGA UMA TABELA
DROP TABLE cliente;